# Change these first
owner: Trocdigital # Your GitHub organization or username, where this repository lives
repo: Navigator-uptime # The name of this repository

sites:
  - name: Navigator 
    url: https://navigator.trocdigital.io/ping
  - name: Navigator API
    url: https://api.trocdigital.io/ping
  - name: Navigator DataIntegrator API Service
    url: https://data.trocdigital.io/ping
  - name: Navigator Frontend Service
    url: https://navigator.trocdigital.io/
  - name: Navigator Monitoring
    url: https://monitor.trocdigital.io/
  - name: Troc ERP
    url: https://troc.erp.trocdigital.io/web/login
  - name: Ticket System  Zammad Trocglobal
    url: https://support.trocdigital.io/
  - name: Ticket System  Odoo Polestar CRM
    url: https://crm.polestarpilates.com/web/login/
    
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /Navigator-uptime
  logoUrl: https://navigator.trocdigital.io/static/icons/favicon.ico
  name: Navigator Status Page
  introTitle: "**Navigator** services uptime monitor and status page."
  introMessage: See below the health check of all Navigator services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
notifications:
  telegram:
    enabled: true
    token: "<TELEGRAM_BOT_API_TOKEN_UPDATE>"
    chat_id: "7617815543"

